name: Sumanta Request Cron Job

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to google.com
        run: |
          response=$(curl -s https://sumantakabiraj.com/)
          echo "::set-output name=response::${response}"
