name: Sumanta Request Cron Job

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
  # Allows manual triggering of the workflow from GitHub's UI
  workflow_dispatch:

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to sumantakabiraj.com
        id: request
        run: |
          response=$(curl -s -I https://sumantakabiraj.com/)
          status_code=$(echo "$response" | grep HTTP/1.1 | awk '{print $2}')
          echo "::set-output name=status_code::${status_code}"
      - name: Print the response
        run: |
          echo "The status code was - ${{ steps.request.outputs.status_code }}"
